### ISSUE TITLE
SWH-LV2 plugins cannot be added to pedalboard

### ISSUE THREAD

**Issue by Rezzonics** [auto3000/meta-pedalpi#15]
plugin.ttl.in not found message
I think 0001 patch is not working properly.
I removed the patch and I got some errors with manifest.ttl files not found, but if i recursively run bitbake I manage to finally build the recipe.
I found that on original swh plugin library there is a patch that adds end of lines (echo -n) on Makefile
https://github.com/swh/lv2/commit/6c8449b66184329027f5b2af3d06a3d7ccf71c46
I was able to add delayorama pedal, though pedal image did not showed up on pedalboard.

**Comment by auto3000** [comment]
Good catch. there is a problem in manifest.ttl files that points to plugin.ttl.in file (that does not exists) instead of plugin-Linux.so. Prior finding the issue, I first used the lv2ls and lv2info commands, very useful. I'm finding now how to fix this in the recipe... 

Meanwhile you can do this command to fix locally:
 sed -i 's/binary <plugin.ttl.in>/binary <plugin-Linux.so>/' /usr/lib/lv2/*-swh.lv2/manifest.ttl

**Comment by auto3000** [comment]
I finally found the problem is an error in one of my old patch to make the recipe... this is why I found the solution quickly.

I did prepare a merge request with the fix on branch swh-fix on meta-pedalpi. I did an image rebuild locally and plugin was successfully imported. Let me know if you can confirm the fix... 

On pedalpi-dev-platform, I also created the temporary branch name is devel/fix-swh-lv2 but you do not really need this.

**Comment by Rezzonics** [comment]
It works
