### ISSUE TITLE
Enhacement: Guitarix LV2 plugins

### ISSUE THREAD

**Issue by Rezzonics** [auto3000/meta-pedalpi#17]
I found this recipe that includes some additional nice pedals:
https://github.com/schnitzeltony/meta-musicians/blob/master/recipes-musicians/guitarix/gxplugins.lv2.bb
I tried master branch wit v0.8 and it builds.
There is a conflict though with 2 duplicated pedals that can be removed from packagegropups:
gxvfm and gxslowgear.
The new pedals appear, however pedal images are not taken, they appear as fish cans.

**Comment by auto3000** [comment]
I will give a try

**Comment by auto3000** [comment]
OK I got it work locally, thanks this plugin set is a good idea.  I tested only a dozen (see capture) from the fifty plugins, and these are really cool.

We will have more than 600 plugins after this integration.
![image](https://user-images.githubusercontent.com/8845975/100499206-ecd97980-3167-11eb-9077-52e0853f37de.png)

I'm preparing a branch (gxplugins-lv2) to check the build are ok on all targets.

After code review of gxvfm and gxslowgear, I think I will remove the recipes because these recipes were building pedal from Git sources from the MOD team. These repos are forked from brummer10 repos to add some generated pedal image (by mod-sdk). Since this fork, it looks brummer10 updates these pedal sw + add custom pedal images which are nicer. It make sense to replace gxvfm and gxslowgear by these new versions.
