### ISSUE TITLE
Enhancement: Add bolliedelay.lv2 plugin

### ISSUE THREAD

**Issue by Rezzonics** [auto3000/meta-pedalpi#20]
Aparently this Bollie Delay LV2 plugin is included in many pedalboards.
I tried to add a recipe but didn't succeeded compiling source files.
It does not find lv2.h include file. It looks for an URI path it cannot find. I guesss I am missing some configuration but not sure what.

**Comment by auto3000** [comment]
I will give a try. Which one boly or boly xt ?

I have a proposal, since I'm quite sure you did 90% of the recipe, you could have put your development branch on this repo. So I could try to review it and give (constructive) feedback. Let say this for next time, I already have almost something :)

**Comment by auto3000** [comment]
![image](https://user-images.githubusercontent.com/8845975/100670030-91251100-335e-11eb-8e7f-8b3b6244277d.png)

It works very well. I put the recipes onto branch dev/bollie. I will merge this since the build is ok in CI (for info, I added odroid-c2 as mandatory build in CI to ensure future changes does not break).

**Comment by Rezzonics** [comment]
I was doing difficult what apparently was easy, I have a lot to learn yet.
Thanks a lot, great job.
