### ISSUE TITLE
fluidplug

### ISSUE THREAD

**Issue by Rezzonics** [auto3000/meta-pedalpi#22]
My first attempt of collaboration.
I made a recipe  for fluidplug lv2 plugins.
I just added a line with the fluidplug recipe on recipes_dev-platform/packagegroups/packagegroup-pedalpii.bb that I did not commit because I have other recipes.
fluidplug recipe works fine but when building pedalpi-dev-platform there is an error when installig packages:
Collected errors:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - nothing provides fluidplug needed by packagegroup-pedalpii-1.0-r0.all
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-pedalpii

**Comment by auto3000** [comment]
a) Not far... The root cause of this problem is your recipe is building correctly, but nothing is in the output package. The output package is generated from the files copied onto destination dir. However nothing was copied to destination dir.

The solution is to add to your recipes these lines to provoke the install of files to proper destination :
EXTRA_OEMAKE = " DESTDIR=${D} "

do_install() {
        oe_runmake install ${EXTRA_OEMAKE}
}

b) But next you will get also a second problem related to "quality assurance". Please try this previous modification first and have a look to error messages. Check this error on documentation on google, because this is something quite recurrent on most recipes.

The solution to this second problem is to force the LINK_OPTS used by the Makefile.mk to zero to make use of Yocto linker flags instead. See the final solution below.

EXTRA_OEMAKE = " DESTDIR=${D} LINK_OPTS= "

c) Finally, could you add the variable SUMMARY and SECTION to the head of the recipe ? After this, I only see the proper license info to set, and you are done.

d) I did not test... I leave you the pleasure to check the visuals of the pedals :) Please let me know if these pedals are interesting.

**Comment by Rezzonics** [comment]
I failed.
There is no license file on the repository I tried to add one manually but
it did not work.
Now it does not even compile, unexpected end of archive on a 7z file, this
is very strange.
I don't know what's broken. Before it compiled properly.

**Comment by auto3000** [comment]
I put my "temporary" copy of your new recipe here in this branch devel/fluidplug-v2 (just in case...)

When the Makefile is not perfect (like with most lv2 git project), bitbake will be unable to rebuild again and again the same recipe. The workaround is to force a "clean" (clean does not only do a "make clean", but a brutal "rm -rf" of the source/build directory) first and relaunch a build with these two commands:
bitbake -c clean fluidplug ; bitbake fluidplug

bitbake -c clean .... is very useful, while it demonstrate something is not well designed in the build system of the underlying package.

**Comment by auto3000** [comment]
About license, I think your recipe is already good except LICENSE = "Unknown"... 
LICENSE = "CC-BY-SA-3.0" must be OK I think.
For reference a list of known licenses: https://git.yoctoproject.org/cgit.cgi/poky/plain/meta/files/common-licenses/

**Comment by Rezzonics** [comment]
I got it working, there was an issue with remote server http://download.linuxaudio.org/
Though  I realized these are not effects but generators, and they need a MIDI sequencer to be used.

**Comment by auto3000** [comment]
Hum OK, I think we can merge this recipe anyway, because someone could plan to connect its midi device (through at midi-to-usb for example), I don't know what do you think.

**Comment by Rezzonics** [comment]
I agree, thanks.
