### ISSUE TITLE
upgradedev: Recipes versions upgrade

### ISSUE THREAD

**Issue by Rezzonics** [auto3000/meta-pedalpi#23]
I created this branch with many version upgrades, specially mod-host and mod-ui.
I also added screenshots and icons for some rakarrack pedals from mod-lv2-data repository.
Many other rakarrack pedals have been removed. They have been removed by moddevices by commenting out the manifest.ttl file, so it should be easy to reinstate them if needed:
https://github.com/moddevices/mod-lv2-data/blob/master/plugins-fixed/rkr.lv2/manifest.ttl
It works on my side.

![Rakarrack-plugins](https://user-images.githubusercontent.com/13797802/101260864-1d568000-3733-11eb-8bcd-da635f211a2b.png)

**Comment by Rezzonics** [comment]
I forgot to tell that I changed a line on /pedalpi-src-build/conf/templates/local.inc

diff --git a/pedalpi-src-build/conf/templates/local.inc b/pedalpi-src-build/conf/templates/local.inc
index b57f86f..89738e9 100644
--- a/pedalpi-src-build/conf/templates/local.inc
+++ b/pedalpi-src-build/conf/templates/local.inc
@@ -6,7 +6,7 @@ PATCHRESOLVE ?= "noop"
 LICENSE_FLAGS_WHITELIST  += "commercial"

 # MOD tools requires a legacy Tornado library
-PREFERRED_VERSION_python3-tornado = "4.2"
+PREFERRED_VERSION_python3-tornado = "4.3"

 # Enable fortran
 FORTRAN_forcevariable = ",fortran"

**Comment by auto3000** [comment]
There is already a recipes-lv2/mod-lv2-data/mod-lv2-data.bb but it probably points to an older version, it make sense to update mod-lv2-data.bb and add the install of rkr plugin. (I'm just surprise all rkr plugins are not enabled because these are all very cool.).
I cannot use your new mod-* tools recipes because the patches are put in comment. Did you try to reapply the patches ?

**Comment by Rezzonics** [comment]
If you prefer, rakarrack-plugins recipe can be included into mod-lv2-data,
pointing to a newer version.
I did a devtool modify recipe mod-host, and manually added some of the most
relevant patches.
Code has changed and the original patches cannot be applied as they are.
I wonder if I screwed up and forgot to make devtool update-recipe, I still
have the modified source code.
Have you tried without the patches? maybe they are not needed, they were mostly logging.

**Comment by Rezzonics** [comment]
@auto3000 I think this is now working, there was some syntax and indentations errors. I didn't know that python was so picky on using tabs and bad indentations. Could you test on your side, I am not very familiar with HMI and pedalPII.

**Comment by auto3000** [comment]
Cool I will give a try

**Comment by auto3000** [comment]
Well I see these problems:
 - alsactl is missing from my installation (i got an error log at boot). I do not really need it but we need to fix this for you.
 - no default pedalboard, consequently on first boot there is no sound at all until we configure one pedalboard
 - my pedalpii python script does not connect to mod-ui, my pedal buttons are disabled (and no LCD display neither) so i have to go on my browser to switch the effects
 - only 550 pedals instead of 600. I think most rkr pedals are missing, anyway you are going in the good direction. We would try to re-enable these rkr pedals next.

On the other side, there are a lot of new pedalboards. I just tried the first two pedalboard and these two are very good. However, a lot of pedalboards are "disabled" with a warning. We are missing some lv2 plugins, but I see that as a good challenge to add any missing pedals to enable all pedalboards.

You did a lot in your branch. I will try to pick each element one by one (I will put you in review). Just to conclude, you did well and this is helping me to focus on problems.

**Comment by Rezzonics** [comment]
Lots of rakarrack pedals have been deprecated on the manifest.ttl file from
moddevices, They have just left the pedals where they added screenshots and
controls and commented out the others. Removing the comments on the
manifest.ttl file will reintroduce those pedals as tin cans. There are
already lots of pedals, but it would be easy to add those missing:
https://github.com/moddevices/mod-lv2-data/blob/master/plugins-fixed/rkr.lv2/manifest.ttl

There is something I am not sure of, but at some point I thought that some
application was looking for data on /root instead of /home/root, at one
point I manually added a symbolic link:
ln -s /home/root /root
but I am not sure if this is required, I don't seem to have the issue of
default pedalboard though.
I was maybe a bit disorganized and try too add too many things at the same
time, that was the reason why I sort of rushed to commit upgradedev branch,
I am not very good with git and checking out different branches.

**Comment by auto3000** [comment]
"There is something I am not sure of, but at some point I thought that some
application was looking for data on /root instead of /home/root, at one"

Oh this reminds me something... I just check... I think this is a side of effect of one modification on your branch:
-export MOD_DATA_DIR=/home/root/data
....
+MOD_DATA_DIR=/home/root/data

Here, "export" is very important to shell, and mod-ui will not inherit from the value MOD_DATA_DIR... consequently mod-ui will try to search to /root instead of /home/root. Your symbolic link is a good workaround.

Don't worry with git, we are all struggling, this is just a matter of time to get experience on this. Actually I'm happy because I just updated mod-host and it works without impact on mod-ui. Now I'm struggling with mod-ui (as usual).

**Comment by Rezzonics** [comment]
I confirm I have no default board pedal, this is not an issue for me
because my only pedal interface is the web.

**Comment by auto3000** [comment]
I did fix the pedalpii python script, the HMI protocol was completely changed but now I'm able to switch the pedalboard. I have still some issues with mod-ui I'm investigating.

**Comment by auto3000** [comment]
I have fixed the problem at MOD-UI startup, I have now a default pedalboard loading... 

Reference to Merge request at https://github.com/auto3000/meta-pedalpi/pull/31

**Comment by auto3000** [comment]
The merge request at https://github.com/auto3000/meta-pedalpi/pull/32 contains the remaining  lv2 recipe upgrade (in split commits) from upgradedev.
